plugins:
  - jekyll-relative-links

# Disable GitHub metadata plugin for local development
github: [metadata]

# Site settings
name: Yorick Brown
title: Full-Stack Developer | Custom WordPress, WooCommerce & API Integrations | Building Scalable, Optimised & Accessible Solutions | JavaScript | PHP | React | OOP
description1: "Welcome to my Github portfolio! I'm a passionate full-stack developer specialising in custom WordPress and WooCommerce solutions."
description2: "With expertise in JavaScript, PHP, React, and OOP, I create scalable, optimised, and accessible web applications tailored to your needs."
author: Yorick Brown
url: https://yodiyo.github.io
logo: /assets/images/dreads-white.png

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name

theme: jekyll-theme-minimal
# OR choose from: cayman, slate, tactile, time-machine, leap-day, modernist, architect, dinky, minima
# remote_theme: pages-themes/minimal@v0.2.0
# Popular: mmistakes/minimal-mistakes, just-the-docs/just-the-docs
relative_links:
  enabled: true
  collections: true
include:
  - PORTFOLIO.md
  - README.md
  - index.md
